spring:
  application:
    name: auth-service

  cloud:
    discovery:
      enabled: false

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb+srv://minh160302:Canhminh-160302@cluster0.6ffh6.mongodb.net/myFirstDatabase?retryWrites=true&w=majority


server:
  port: 8200


#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

