spring:
  application:
    name: auth-service

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://localhost:27017/user_db


server:
  port: 8200

#
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

